apiVersion: v1
kind: Pod
metadata:
  name: vault-example
  labels:
    name: demo
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "sql-role"
    vault.hashicorp.com/tls-skip-verify: "true"
    vault.hashicorp.com/agent-inject-secret-sql-role: "database/creds/sql-role"
    vault.hashicorp.com/agent-inject-template-sql-role: |
          {
          {{- with secret "database/creds/sql-role" -}}
            "db_connection": "host=postgres-0.postgres-svc.default.svc.cluster.local port=5432 user={{ .Data.username }} password={{ .Data.password }} dbname=testdb sslmode=disable"
          {{- end }}
          }
spec:
  serviceAccountName: dynamic-postgres
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"