apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mutating-webhook-certs
  namespace: default
spec:
  secretName: mutating-webhook-certs
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: mutating-webhook.default.svc
  dnsNames:
    - mutating-webhook.default.svc
    - mutating-webhook.default.svc.cluster.local
  isCA: true
