apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutating-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutating-webhook
  template:
    metadata:
      labels:
        app: mutating-webhook
    spec:
      containers:
        - name: webhook
          image: ivanklivitskyi/python-test:3
          imagePullPolicy: Always
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: certs
              mountPath: "/certs"
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: mutating-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: mutating-webhook
  namespace: default
spec:
  ports:
    - port: 443
      targetPort: 8123
  selector:
    app: mutating-webhook
