apiVersion: v1
kind: Pod
metadata:
  name: vault-example
  labels:
    name: demo
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "basic-secret-role"
    vault.hashicorp.com/tls-skip-verify: "true"
    vault.hashicorp.com/agent-inject-secret-mysecret: "secret/basic-secret/test"
spec:
  serviceAccountName: basic-secret
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"